### ISSUE TITLE
MineFix and mcimport collaboration

### ISSUE THREAD

**Issue by Avamander** [minetest-tools/mcimport#13]
What do you think about adding support for blocks provided by the [MineFix](https://github.com/Minefix/MineFix) modpack? Plus in the future work towards perfect Minecraft compatibility?

**Comment by sofar** [comment]
Link? I haven't seen MineFix.

**Comment by Avamander** [comment]
Sorry, here's a link: https://github.com/Minefix/MineFix

**Comment by sofar** [comment]
Sorry, I should have replied back earlier.

The goal of this tool is NOT to recreate minecraft 1:1. The goal is to convert the world into a playable minetest equivalent, without going out of the way to create a perfect minecraft world that behaves exactly the same. I'll leave that effort to others.
