### ISSUE TITLE
I tried to convert my MC world to MT, but it seems to fail. 

### ISSUE THREAD

**Issue by Pantyhose-X** [minetest-tools/mcimport#34]
@sofar @ShadowNinja @Ekdohibs @ensonic @MysticTempest @dgm3333 @Schmeldric @zaoqi @FaceDeer
* system: Linux Manjaro Win10
* versions: Minecraft Java 1.12.2 
* map: [map](https://www.planetminecraft.com/project/novigrad-timelapse-download/)
 No building 
video https://vimeo.com/manage/videos/538964253

[![Ivideo](https://i.vimeocdn.com/video/1115862017.webp?mw=600&mh=339)](https://vimeo.com/manage/videos/538964253)

**Comment by MysticTempest** [comment]
Currently; you need to find the minecraft coordinates, and convert them before teleporting to the minetest ones.

```
Coordinate Conversion from Minecraft to Minetest:

X = Approximately the same in both.
Y = Approximately -64 nodes.
Z = The number is approximately inverted.

A general example of converted coordinates:
Minecraft: 704, 4, -318
Minetest: 720, -60, 334
```

I took a quick look at that map's coordinates in minecraft. You'll need to teleport/fly to the following coordinates in your converted world. 

```
/grantme all
/teleport 904,25,-1217
```
It'll load you into part of the converted map. 
You'll also need the WorldMods from the included shell script. I'm not sure if you downloaded those offscreen, or what; but they're needed as well.

**Comment by Pantyhose-X** [comment]
> Currently; you need to find the minecraft coordinates, and convert them before teleporting to the minetest ones.
> 
> ```
> Coordinate Conversion from Minecraft to Minetest:
> 
> X = Approximately the same in both.
> Y = Approximately -64 nodes.
> Z = The number is approximately inverted.
> 
> A general example of converted coordinates:
> Minecraft: 704, 4, -318
> Minetest: 720, -60, 334
> ```
> 
> I took a quick look at that map's coordinates in minecraft. You'll need to teleport/fly to the following coordinates in your converted world.
> 
> ```
> /grantme all
> /teleport 904,25,-1217
> ```
> 
> It'll load you into part of the converted map.
> You'll also need the WorldMods from the included shell script. I'm not sure if you downloaded those offscreen, or what; but they're needed as well.

Thank you bro
```
Coordinate Conversion from Minecraft to Minetest:

X = Approximately +16 nodes
Y = Approximately -64 nodes
Z = The number is approximately inverted. -16 nodes
```
