### ISSUE TITLE
more details for "Unknown Minecraft Block:52:0"

### ISSUE THREAD

**Issue by ensonic** [minetest-tools/mcimport#5]
What does the ":52:0" stand for? Any guidance what to do to improve coverage?

The README only mentions 'missing mode' which is a bit vague. How do I find out what mod I would need to install?

**Comment by sofar** [comment]
These are missing mappings, not fixable by installing mods.

**Comment by ensonic** [comment]
Would it make sense to have a line format for not-yet mapped blocks, then the code could output them with a readable name (I see that map_content.txt already has //TODO comments for some of them). If I got it right the ids are those e.g. listed on http://minecraft-ids.grahamedgecombe.com/

I'll send a PR later to write Unknown Minecraft Block messages to stderr so that one can easilly redirect them to a file and get some stats: sort missing.txt | uniq -c | sort -n

**Comment by sofar** [comment]
acd7eaa4446ede45136b10923325e08a00cd03a7

**Comment by ensonic** [comment]
Any info on what the 2nd number on the chests is about?

**Comment by sofar** [comment]
Likely rotation.
